title: Users
modelClass: GeeksLab\User\Models\User
list: $/geekslab/user/models/user/columns.yaml
recordUrl: 'geekslab/user/users/preview/:id'
noRecordsMessage: 'backend::lang.list.no_records'
recordsPerPage: 20
showSetup: true
showCheckboxes: true
defaultSort:
    column: id
    direction: desc
toolbar:
    buttons: list_toolbar
    search:
        prompt: 'backend::lang.list.search_prompt'
filter: filter_config
